config/routes.rb
Rails.application.routes.draw do
  root "railway_stations#index"

  resources :railway_stations do
    patch :update_position, on: :member
  end
  resources :routes
  resources :trains do
    resources :carriages
  end
  resources :carriages

  get '/tickets/search', to: 'tickets#search'
  #get '/tickets', to: 'tickets#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :route, optional: true
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id, optional: true

  has_many :carriages, -> (train) { order("number #{train.carriage_sorting ? 'ASC' : 'DESC'}") }, dependent: :destroy
  has_many :compartment_carriages
  has_many :econom_carriages
  has_many :sv_carriages
  has_many :chair_carriages

  has_many :tickets

  def rsrs_by_arrival_and_departure(arrival_station_id, departure_station_id)
    #[arrival_station, departure_station].map{ |station_id| route.railway_stations_routes}
    rsrs = route.railway_stations_routes.where(railway_station_id: [arrival_station_id, departure_station_id])
    rsrs.pluck(:id) == [arrival_station_id, departure_station_id] ? rsrs : []


  end

  def carriages_info(carriage_type, seats_type)
    carriages.where(type: carriage_type.camelize).sum(seats_type)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[show edit update destroy]

  # GET /trains or /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1 or /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains or /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: "Train was successfully created." }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1 or /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: "Train was successfully updated." }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1 or /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: "Train was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def train_params
      params.require(:train).permit(:number, :route_id, :carriage_sorting )
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_with(model: train) do |form| %>
  <%= render ' shared/errors', object: train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.collection_select :route_id, Route.order(:name), :id, :name, { prompt: 'Select route'} %>
  </div>

  <div class="field">
    <%= form.label :carriages_sorting %>
    <span> ASC </span>
    <%= form.radio_button :carriage_sorting, true %>
    <span> DESC </span>
    <%= form.radio_button :carriage_sorting, false %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= train.route ? train.route.name : 'No route name specified'  %></td>
  <td><%= link_to 'Show', train %></td>
  <td><%= link_to 'Edit', edit_train_path(train) %></td>
  <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Edit Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Route name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>Route name:</strong>
  <%= @train.route ? @train.route.name : 'No route name specified' %>
</p>

<p>
  <strong>Carriages:</strong>
  <% if @train.carriages.any? %>
    <% @train.carriages.each do |carriage| %>
      <%= link_to carriage.position, train_carriage_path(@train, carriage) %>
    <% end %>
  <% else %>
    No carriages attached
  <% end %>
</p>

<% Carriage::TYPES.each do |ct| %>
  <% seats = ct.pluralize %>

  <% if @train.respond_to?(seats) && @train.send(seats).any? %>
    <p>
      <strong>Number of <%= ct.humanize %>s:</strong>
      <%= @train.send(seats).size %>
    </p>

    <% ct.camelize.constantize::SEAT_TYPES.each do |seat_type| %>
      <p>
        <strong> total <%= seat_type %></strong>
        <%= @train.send(seats).sum(seat_type) %>
      </p>
    <% end  %>
    <br>
  <% end %>
<% end %>

<% Carriage::TYPES.map(&:camelize).each do |carriage_type| %>
  <%= link_to "New #{carriage_type}", new_train_carriage_path(@train, carriage: { type: carriage_type }) %> |
<% end %>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>