config/routes.rb
Rails.application.routes.draw do
  root "railway_stations#index"

  resources :railway_stations do
    patch :update_position, on: :member
  end
  resources :routes
  resources :trains do
    resources :carriages
  end
  resources :carriages

  get '/tickets/search', to: 'tickets#search'
  #get '/tickets', to: 'tickets#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  TYPES = %w(compartment_carriage econom_carriage sv_carriage chair_carriage)

  belongs_to :train

  validates :position, uniqueness: { allow_nil: true, scope: :train_id }

  before_validation :set_position

  private

  def set_position
    self.position = train.carriages.pluck(:position).max.to_i + 1
  end
end

app/controllers/carriages_controller.rb
class CarriagesController < ApplicationController
  before_action :set_train, only: %i[new create]
  before_action :set_carriage, only: %i[show edit update destroy]

  def index
    @carriages = Carriage.all
  end

  def show
  end

  def new
    @carriage = Carriage.new
  end

  def edit
  end

  def create
    @carriage = @train.carriages.new(carriage_params)

    if @carriage.save
      #redirect_to carriage_path(@carriage), notice: "Carriage was successfully created."
      redirect_to @train, notice: "Carriage was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    respond_to do |format|
      if @carriage.update(carriage_params)
        format.html { redirect_to carriage_path(@carriage), notice: "Carriage was successfully updated." }
        format.json { render :show, status: :ok, location: @carriage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carriage.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @carriage.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: "Carriage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_carriage
    @carriage = Carriage.find(params[:id]).becomes(Carriage)
  end

  def set_train
    return unless params[:train_id]

    @train =  Train.find(params[:train_id])
  end

  def carriage_params
    params.require(:carriage).permit(
      :number, :type, :upper_seats, :lower_seats, :side_lower_seats, :side_upper_seats, :chair_seats, :train_id
    )
  end
end

app/helpers/carriages_helper.rb
module CarriagesHelper
end

app/views/carriages/_carriage.html.erb
<tr>
  <td><%= carriage.number %></td>

<!--  <td>Route name: <%#= carriage.route ? carriage.route.name : 'No route specified'  %></td>-->
  <td><%= link_to 'Show', carriage_path(carriage) %></td>
  <td><%= link_to 'Edit', edit_carriage_path(carriage) %></td>
  <td><%= link_to 'Destroy', carriage_path(carriage), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/carriages/_form.html.erb
<%= form_for([@train, @carriage.becomes(Carriage)]) do |form| %>
  <%= render ' shared/errors', object: @carriage %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :train_id %>
    <% if action_name == 'edit' %>
      <%= form.select :train_id, [[ @carriage.train.number,  @carriage.train_id ]] %>
    <% else %>
      <%= form.collection_select :train_id, Train.order(:number), :id, :number, { prompt: 'Select train'} %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :type, ([ (params.dig(:carriage, :type) || @carriage.type) ]) %>
  </div>

  <% (params.dig(:carriage, :type) || @carriage.type).constantize::SEAT_TYPES.each do |seat_type| %>
    <div class="field">
      <%= form.label seat_type %>
      <%= form.range_field seat_type, in: 1..100 %>
    </div>
  <% end  %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carriages/edit.html.erb
<h1>Edit Carriage</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to 'Show', @carriage %> |
<%= link_to 'Back', carriages_path %>

app/views/carriages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carriages</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: "carriage", collection: @carriages %>
  </tbody>
</table>

app/views/carriages/new.html.erb
<h1>New Carriage</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to 'Back', carriages_path %>

app/views/carriages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @carriage.number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @carriage.type %>
</p>

<p>
  <strong>Train:</strong>
  <%= @carriage.train.number %>
</p>

<% @carriage.type.constantize::SEAT_TYPES.each do |seat_type| %>
  <p>
    <strong><%= seat_type %></strong>
    <%= @carriage.send(seat_type) %>
  </p>
<% end %>

<p>
  <strong>Position:</strong>
  <%= @carriage.position ? @carriage.position : 'Not specified' %>
</p>

<%= link_to 'Edit', edit_carriage_path(@carriage) %> |
<%= link_to 'Back', carriages_path %>