config/routes.rb
Rails.application.routes.draw do
  root "railway_stations#index"

  resources :railway_stations do
    patch :update_position, on: :member
  end
  resources :routes
  resources :trains do
    resources :carriages
  end
  resources :carriages

  get '/tickets/search', to: 'tickets#search'
  #get '/tickets', to: 'tickets#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  has_many :trains

  validates :name, presence: true
end

app/controllers/routes_controller.rb
  class RoutesController < ApplicationController
  before_action :initialize_route, only: %i[new]
  before_action :find_route, only: %i[show edit update destroy]
  before_action :create_railway_stations_routes, only: %i[update]

  def index
    @routes = Route.all
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to route_path(@route), notice: 'Route created'
    else
      render :new, notice: 'Something went wrong'
    end
  end

  def update
    #byebug
    if @route.update(route_params)
      redirect_to @route, notice: 'Route updated'
    else
      render :edit, notice: 'Something went wrong'
    end
  end

  def destroy
    if @route.destroy
      redirect_to routes_path, notice: 'Route has been deleted'
    else
      redirect_to @route, notice: 'Something went wrong'
    end
  end

  private

  def create_railway_stations_routes
    railway_station_ids = params.dig(:route, :railway_station_ids)
    if railway_station_ids.any?
      railway_station_ids.delete('')

      railway_station_ids.each do |railway_station_id|
        byebug
        railway_station = RailwayStation.find_by(railway_station_id)

        RailwayStationsRoute.find_or_create_by(route: @route, railway_station: railway_station)
      end
    end
  end

  def initialize_route
    @route = Route.new
  end

  def find_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/views/routes/_form.html.erb
<%= form_with(model: route) do |form| %>
  <%= render ' shared/errors', object: route %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :railway_stations  %>
    <%= form.collection_select(:railway_station_ids, RailwayStation.order(:title), :id, :title, { prompt: ('Select stations')}, {multiple: true}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Edit Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice || alert %></p>

<h1>Routes</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @routes.each do |route| %>
    <tr>
      <td><%= route.name %></td>
      <td><%= link_to 'Show', route %></td>
      <td><%= link_to 'Edit', edit_route_path(route) %></td>
      <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<p>
  <strong>Trains on the route:</strong>

  <% if @route.trains.any? %>
    <% @route.trains.each do |train| %>
      <%= train.number %>
    <% end %>
  <% else %>
    No trains on the route
  <% end %>
</p>

<p>
  <strong>List of route stations:</strong>
  <% if @route.railway_stations.any? %>
    <table>
      <thead>
        <tr>
          <td>name</td>
          <td>position</td>
        </tr>
      </thead>
      <tbody>
        <% @route.railway_stations.ordered_by_position.each do |railway_station| %>
          <tr>
            <td><%= railway_station.title %></td>
            <td>
              <%= render partial: 'railway_stations/position_form',
                         locals: {route: @route, railway_station: railway_station} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    Route does not include stations
  <% end %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>